/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentetextfield;

/**
 *
 * @author alumnop
 */
public class DatosTextFieldPanel extends javax.swing.JPanel {

    /**
     * Creates new form DatosTextFieldPanel
     */
    
    public DatosTextFieldPanel() {
        initComponents();
    }
    
    public DatosTextField getValores(){
        int longit=0;

        if (!jTextFieldLongitud.getText().equals("")) longit=Integer.parseInt(jTextFieldLongitud.getText());

        return new DatosTextField(longit, jRadioButtonNumerico.isSelected(), jRadioButtonAlfabetico.isSelected());            

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLongitud = new javax.swing.JTextField();
        jRadioButtonNumerico = new javax.swing.JRadioButton();
        jRadioButtonAlfabetico = new javax.swing.JRadioButton();

        jLabel1.setText("Longitud:");

        jTextFieldLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLongitudKeyTyped(evt);
            }
        });

        buttonGroup.add(jRadioButtonNumerico);
        jRadioButtonNumerico.setText("Numérico");

        buttonGroup.add(jRadioButtonAlfabetico);
        jRadioButtonAlfabetico.setText("Alfabético");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonNumerico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonAlfabetico)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNumerico)
                    .addComponent(jRadioButtonAlfabetico))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLongitudKeyTyped
        // Verificar si la tecla pulsada no es un digito (en este caso anulo el evento)
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) 
        {
           evt.consume();  // ignorar el evento de teclado
        }     
    }//GEN-LAST:event_jTextFieldLongitudKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonAlfabetico;
    private javax.swing.JRadioButton jRadioButtonNumerico;
    private javax.swing.JTextField jTextFieldLongitud;
    // End of variables declaration//GEN-END:variables
}
