/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componenteBotonMorse;

/**
 *
 * @author Eduardo
 */
public class DuracionPulsacionesPanel extends javax.swing.JPanel {

    /**
     * Creates new form DuracionPulsacionesPanel
     */
    public DuracionPulsacionesPanel() {
        initComponents();
    }
    
    public DuracionPulsaciones getValoresSeleccionados(){
           //Método que recoge los valores seleccionados
           
           int valorCorto,valorLargo;
           
           if(!jTextFieldDuracionPulsacionCorta.getText().equals(""))
                 valorCorto=Integer.parseInt(jTextFieldDuracionPulsacionCorta.getText()); 
           else valorCorto=0;
           if(!jTextFieldDuracionPulsacionLarga.getText().equals(""))
                 valorLargo=Integer.parseInt(jTextFieldDuracionPulsacionLarga.getText()); 
           else valorLargo=0;           
           return new DuracionPulsaciones(valorCorto,valorLargo); //devuelvo el objeto
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDuracionPulsacionCorta = new javax.swing.JTextField();
        jTextFieldDuracionPulsacionLarga = new javax.swing.JTextField();

        jLabel1.setText("Duración pulsación Corta:");

        jLabel2.setText("Duración Pulsación Larga:");

        jTextFieldDuracionPulsacionCorta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDuracionPulsacionCortaKeyTyped(evt);
            }
        });

        jTextFieldDuracionPulsacionLarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDuracionPulsacionLargaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDuracionPulsacionCorta)
                    .addComponent(jTextFieldDuracionPulsacionLarga, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDuracionPulsacionCorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDuracionPulsacionLarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDuracionPulsacionCortaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDuracionPulsacionCortaKeyTyped
      char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if ((caracter < '0') || (caracter > '9')) 
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextFieldDuracionPulsacionCortaKeyTyped

    private void jTextFieldDuracionPulsacionLargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDuracionPulsacionLargaKeyTyped
      char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if ((caracter < '0') || (caracter > '9')) 
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextFieldDuracionPulsacionLargaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldDuracionPulsacionCorta;
    private javax.swing.JTextField jTextFieldDuracionPulsacionLarga;
    // End of variables declaration//GEN-END:variables
}
