/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IngresosGastosHelp.gui;

import IngresosGastosHelp.dto.IngresoGasto;
import IngresosGastosHelp.logica.LogicaNegocio;
import java.io.File;
import java.net.URL;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.MainWindow;

/**
 *
 * @author Eduardo
 */
public class JDialogAlta extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAlta
     */
    public JDialogAlta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Metemos la ayuda
        try 
        {
            // Carga el fichero de ayuda
            File fichero = new File("src"+File.separator+"help"+File.separator+"help_set.hs");
            URL hsURL = fichero.toURI().toURL();
            // Crea el HelpSet y el HelpBroker            
            HelpSet helpset = new HelpSet(null, hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // al pulsar F1 en la ventana sale la ayuda
            hb.enableHelpKey(getRootPane(),"ventana_alta",helpset);
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }           
        setLocationRelativeTo(parent); //localización relativa al padre
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelfechaAlta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelImporte = new javax.swing.JLabel();
        jTextFieldImporte = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldConcepto = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelfechaAlta.setText("Fecha:");

        jLabel1.setText("Concepto:");

        jLabelImporte.setText("Importe:");

        jTextFieldImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldImporteKeyTyped(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldConcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldConceptoKeyTyped(evt);
            }
        });

        jTextFieldFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFechaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImporte)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelfechaAlta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelfechaAlta)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImporte))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
 
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        //guardamos los datos pero antes comprobamos si se cumple la validación de los datos
        if (validaDatos()){
            SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy"); //formateamos la fecha
            try{
                Date fecha = formateador.parse(jTextFieldFecha.getText()); 
                IngresoGasto ingresoGasto=new IngresoGasto(fecha,jTextFieldConcepto.getText(),Float.parseFloat(jTextFieldImporte.getText()));
                LogicaNegocio.anadirIngresoGasto(ingresoGasto);
                dispose(); 
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Se ha producido un error al guardar los datos","Error",JOptionPane.ERROR_MESSAGE);
            }            
        }

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldImporteKeyTyped
        //Expresión regular que identifica un número entero o real
        Pattern pat = Pattern.compile("^-?[0-9]*[\\.]?[0-9]*$"); //esta expresión regular es distinta a la que evalua el numero entero ya que tiene que ir permitiendonos introducir uno a uno sus caracteres sin dar error
        Matcher real = pat.matcher(jTextFieldImporte.getText()+evt.getKeyChar()); //En el valor del textfield aun no está la tecla pulsada (por eso se la añadimos)
        if (!(real.matches()))  //si no se cumple la expresión regular anula el evento del teclado
            evt.consume();  // ignorar el evento de teclado
        //Puede ser también así:
        //if (!Pattern.matches("^-?[0-9]*[\\.]?[0-9]*$", jTextFieldImporte.getText()+evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_jTextFieldImporteKeyTyped

    private void jTextFieldConceptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConceptoKeyTyped
        // Vamos a hacer que el concepto no pase de 40 carácteres
        int num_caract=jTextFieldConcepto.getText().length()+1; //En el valor del textfield aun no está el caracter pulsado (por eso se suma 1)
        if (num_caract>40) { //si no se cumple la expresión regular anula el evento del teclado
            evt.consume();  // ignorar el evento de teclado
        }        
    }//GEN-LAST:event_jTextFieldConceptoKeyTyped

    private void jTextFieldFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFechaKeyTyped
        //chequeamos que solo se metan los caracteres 0..9 y el /

        if (!((evt.getKeyChar()>='0'&&evt.getKeyChar()<='9')||(evt.getKeyChar()=='/'))) { 
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jTextFieldFechaKeyTyped

    private boolean validaDatos(){ //Método que valida los datos a guardar
        boolean res=true;
        String msn="";
        if ((jTextFieldFecha.getText().isEmpty())||("".equals(jTextFieldFecha.getText()))){ //en caso de que no venga el importe
            res=false;
            msn="La fecha es obligatoria \n";
        }        
        if ((jTextFieldConcepto.getText().isEmpty())||("".equals(jTextFieldConcepto.getText()))){ //en caso de que no venga el concepto
            res=false;
            msn="El concepto es obligatorio \n";
        }
        if ((jTextFieldImporte.getText().isEmpty())||("".equals(jTextFieldImporte.getText()))){ //en caso de que no venga el concepto
            res=false;
            msn=msn+"El importe es obligatorio \n";
        }
        if (!Pattern.matches("^([0][1-9]|[12][0-9]|3[01])((/|-)([0][1-9]|[1][0-2]))((\\/|-)(\\d{4}))$", jTextFieldFecha.getText())){
            res=false;
            msn=msn+"No es una fecha válida dd/mm/aaaa \n";
        }
        if (!Pattern.matches("^-?[0-9]*([\\.]?[0-9]+)?$", jTextFieldImporte.getText())){ //puede ser un número con signo - o no, y llevar o no decimales
            res=false;
            msn=msn+"No es un formato de importe correcto \n";
        }
        if (!res){
            JOptionPane.showMessageDialog(this,msn,"Error",JOptionPane.ERROR_MESSAGE);
        }
        return res;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAlta dialog = new JDialogAlta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImporte;
    private javax.swing.JLabel jLabelfechaAlta;
    private javax.swing.JTextField jTextFieldConcepto;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldImporte;
    // End of variables declaration//GEN-END:variables
}
