/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtextfieldcolorvalor;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JColorChooser;

/**
 *
 * @author Eduardo
 */
public class ValoresChequeoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ValoresChequeoPropertyEditor
     */
    private Color colorSuperior=Color.BLACK;
    private Color colorInferior=Color.RED;    
    public ValoresChequeoPanel() {
        initComponents();
    }
    public ValoresChequeo getValoresSeleccionados(){
           //Método que recoge los valores seleccionados
           
           Float valor;
           if(!jTextFieldValor.getText().equals(""))
                 valor=Float.parseFloat(jTextFieldValor.getText()); //pasamos el valor de textField a Float
           else valor=0f;
           
           return new ValoresChequeo(colorSuperior.getRGB(),colorInferior.getRGB(),valor); //devuelvo el objeto
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImporte = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelImporte1 = new javax.swing.JLabel();
        jTextFieldColorSuperior = new javax.swing.JTextField();
        jButtonSuperior = new javax.swing.JButton();
        jLabelImporte2 = new javax.swing.JLabel();
        jTextFieldColorInferior = new javax.swing.JTextField();
        jButtonInferior = new javax.swing.JButton();

        jLabelImporte.setText("Valor Mínimo:");

        jTextFieldValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorKeyTyped(evt);
            }
        });

        jLabelImporte1.setText("Color Superior:");

        jButtonSuperior.setText("Seleccionar ...");
        jButtonSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuperiorActionPerformed(evt);
            }
        });

        jLabelImporte2.setText("Color Inferior:");

        jButtonInferior.setText("Seleccionar ...");
        jButtonInferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInferiorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImporte2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldColorInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelImporte1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldColorSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelImporte)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImporte))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImporte1)
                    .addComponent(jTextFieldColorSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSuperior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImporte2)
                    .addComponent(jTextFieldColorInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInferior))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorKeyTyped
        //Expresión regular que identifica un número entero o real
        Pattern pat = Pattern.compile("^-?[0-9]*[\\.]?[0-9]*$"); //esta expresión regular es distinta a la que evalua el numero entero ya que tiene que ir permitiendonos introducir uno a uno sus caracteres sin dar error
        Matcher real = pat.matcher(jTextFieldValor.getText()+evt.getKeyChar()); //En el valor del textfield aun no está la tecla pulsada (por eso se la añadimos)
        if (!(real.matches()))  //si no se cumple la expresión regular anula el evento del teclado
              evt.consume();  // ignorar el evento de teclado
        //Puede ser también así:
        //if (!Pattern.matches("^-?[0-9]*[\\.]?[0-9]*$", jTextFieldImporte.getText()+evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_jTextFieldValorKeyTyped

    private void jButtonSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuperiorActionPerformed
        JColorChooser jc = new JColorChooser(); 
        colorSuperior=jc.showDialog(this, "Seleccione un Color", Color.BLACK);  
        jTextFieldColorSuperior.setText(Integer.toString(colorSuperior.getRGB()));
    }//GEN-LAST:event_jButtonSuperiorActionPerformed

    private void jButtonInferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInferiorActionPerformed
        JColorChooser jc = new JColorChooser(); 
        colorInferior=jc.showDialog(this, "Seleccione un Color", Color.RED);  
        jTextFieldColorInferior.setText(Integer.toString(colorInferior.getRGB()));
    }//GEN-LAST:event_jButtonInferiorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInferior;
    private javax.swing.JButton jButtonSuperior;
    private javax.swing.JLabel jLabelImporte;
    private javax.swing.JLabel jLabelImporte1;
    private javax.swing.JLabel jLabelImporte2;
    private javax.swing.JTextField jTextFieldColorInferior;
    private javax.swing.JTextField jTextFieldColorSuperior;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
