/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leerficheros;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author Eduardo
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    private int numActual = 0;

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldRuta = new javax.swing.JTextField();
        jButtonSelecRuta = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jButtonBuscar = new javax.swing.JButton();
        jLabelFichCopiado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldRuta.setEditable(false);

        jButtonSelecRuta.setText("...");
        jButtonSelecRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecRutaActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setEnabled(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jButtonSelecRuta)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabelFichCopiado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelecRuta))
                .addGap(35, 35, 35)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelFichCopiado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonBuscar)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecRutaActionPerformed
        jProgressBar.setValue(0);
        jProgressBar.repaint();
        JFileChooser jc = new JFileChooser();
        jc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = jc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            jButtonSelecRuta.setEnabled(false);
            jButtonBuscar.setEnabled(false);
            Thread queryThread = new Thread() {
                public void run() {
                    numArchivos(jc.getSelectedFile());
                }
            };
            queryThread.start();
        } else if (result == JFileChooser.CANCEL_OPTION) {
            jTextFieldRuta.setText("");
            jButtonBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonSelecRutaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        jButtonSelecRuta.setEnabled(false);
        jButtonBuscar.setEnabled(false);
        Thread queryThread = new Thread() {
            public void run() {
                File file = new File(jTextFieldRuta.getText());
                buscaDirectorios(file);
                updateComponentesTerminarBuscar();
            }
        };
        queryThread.start();
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    private void numArchivos(File f) {
        updateComponentesSeleccionar(getDirSize(f), f.getAbsolutePath());
    }

    private void buscaDirectorios(File dir) {

        File listFile[] = dir.listFiles();
        if (listFile != null && listFile.length > 0) {
            for (int i = 0; i < listFile.length; i++) {
                if (listFile[i].isDirectory()) {
                    buscaDirectorios(listFile[i]);
                } else {
                  
                    updateComponentesBuscar(listFile[i].getName(), numActual++);
                }

            }
        }
    }

    private void updateComponentesBuscar(String fichero, int porcentaje) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                    jLabelFichCopiado.setText(fichero);
                    jProgressBar.setValue(porcentaje);
                    jProgressBar.repaint();                        
            }
        });
    }

    private void updateComponentesSeleccionar(int numArchivos, String ruta) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jTextFieldRuta.setText(ruta);
                jProgressBar.setMaximum(numArchivos);
                jButtonSelecRuta.setEnabled(true);
                jButtonBuscar.setEnabled(true);
            }
        });
    }

    private void updateComponentesTerminarBuscar() {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jButtonSelecRuta.setEnabled(true);
                jButtonBuscar.setEnabled(true);
            }
        });
    }

    public static int getDirSize(File directory) {
        int size = 0;

        if (directory.listFiles() != null) {
            for (File file : directory.listFiles()) {
                size += file.isDirectory() ? getDirSize(file) : 1;
            }
        }
        return size;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonSelecRuta;
    private javax.swing.JLabel jLabelFichCopiado;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JTextField jTextFieldRuta;
    // End of variables declaration//GEN-END:variables
}
