/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dialog;

/**
 *
 * @author Eduardo
 */
public class VentanaSecundaria1 extends javax.swing.JDialog {

    /**
     * Creates new form VentanaSecundaria2
     */
    public VentanaSecundaria1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumeroVentana = new javax.swing.JLabel();
        jButtonVolver1 = new javax.swing.JButton();
        jButtonAbrirVentana1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNumeroVentana.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelNumeroVentana.setForeground(new java.awt.Color(255, 0, 51));
        jLabelNumeroVentana.setText("Ventana 1");

        jButtonVolver1.setText("Volver");
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ActionPerformed(evt);
            }
        });

        jButtonAbrirVentana1.setText("Abrir Ventana");
        jButtonAbrirVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirVentana1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabelNumeroVentana))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButtonAbrirVentana1)
                        .addGap(58, 58, 58)
                        .addComponent(jButtonVolver1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelNumeroVentana)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver1)
                    .addComponent(jButtonAbrirVentana1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver1ActionPerformed
        
        dispose();
    }//GEN-LAST:event_jButtonVolver1ActionPerformed

    private void jButtonAbrirVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirVentana1ActionPerformed
        VentanaSecundaria3 Ventana3=new VentanaSecundaria3(this,false);
        Ventana3.setModalityType(Dialog.ModalityType.APPLICATION_MODAL  );
        Ventana3.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirVentana1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirVentana1;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JLabel jLabelNumeroVentana;
    // End of variables declaration//GEN-END:variables
}
