/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dialog;

/**
 *
 * @author Eduardo
 */
public class VentanaSecundaria4 extends javax.swing.JDialog {

    /**
     * Creates new form VentanaSecundaria2
     */
    public VentanaSecundaria4(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumeroVentana4 = new javax.swing.JLabel();
        jButtonVolver4 = new javax.swing.JButton();
        jButtonAbrirVentana4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNumeroVentana4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelNumeroVentana4.setForeground(new java.awt.Color(255, 0, 51));
        jLabelNumeroVentana4.setText("Ventana 4");

        jButtonVolver4.setText("Volver");
        jButtonVolver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver4ActionPerformed(evt);
            }
        });

        jButtonAbrirVentana4.setText("Abrir Ventana");
        jButtonAbrirVentana4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirVentana4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabelNumeroVentana4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButtonAbrirVentana4)
                        .addGap(58, 58, 58)
                        .addComponent(jButtonVolver4)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelNumeroVentana4)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver4)
                    .addComponent(jButtonAbrirVentana4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver4ActionPerformed
        
        dispose();
    }//GEN-LAST:event_jButtonVolver4ActionPerformed

    private void jButtonAbrirVentana4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirVentana4ActionPerformed

    }//GEN-LAST:event_jButtonAbrirVentana4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirVentana4;
    private javax.swing.JButton jButtonVolver4;
    private javax.swing.JLabel jLabelNumeroVentana4;
    // End of variables declaration//GEN-END:variables
}
